server:
  port: 31001
spring:
  application:
    name: xc-service-cms
  data:
    mongodb:
      uri: mongodb://tangjiejin:123456@localhost:27017
      database: xc_cms
  rabbitmq:
    host: localhost
    port: 5672
    username: tangjiejin
    password: 123456
    virtualHost: /
